spring.datasource.url=jdbc:mysql://localhost:3306/rideshare_db
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

gemini.api.key=AIzaSyC8Oz1fOMwwTV_i_j1a9bfDHp86SNvc4I0

server.port=8080